version: '3'
services:
  app01:
    build: ./docker/app
    container_name: isucon7-app01
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 8081:80
    depends_on:
      - app03
    links:
      - app03
  app02:
    build: ./docker/app
    container_name: isucon7-app02
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 8082:80
    depends_on:
      - app03
    links:
      - app03
  app03:
    build: ./docker/db
    container_name: isucon7-app03
    restart: always
    stdin_open: true
    privileged: true
    volumes:
      - .:/home/isucon/isubata
      - ./docker/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3306
    # command: sudo mysqld_safe --port=3306
  bench:
    build: ./docker/app
    container_name: isucon7-bench
    restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 3000