version: '3'
services:
  app01:
    build: ./docker
    container_name: isucon7-app01
    # restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
      # - ./files/app/nginx.01.conf:/etc/nginx/conf.d/nginx.01.conf
      # - ./files/app/nginx.01.conf.php:/etc/nginx/conf.d/nginx.01.conf.php
    ports:
      - 8081:80
    environment:
      - MYSQL_HOST=app03
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - app03
    links:
      - app03
    # command: sudo /usr/sbin/nginx -g 'daemon off;'
  app02:
    build: ./docker
    container_name: isucon7-app02
    # restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
      # - ./files/app/nginx.02.conf:/etc/nginx/conf.d/nginx.02.conf
      # - ./files/app/nginx.02.conf.php:/etc/nginx/conf.d/nginx.02.conf.php
    ports:
      - 8082:80
    environment:
      - MYSQL_HOST=app03
      - USER=root
      - MYSQL_PWD=root
    depends_on:
      - app03
    links:
      - app03
    # command: sudo /usr/sbin/nginx -g 'daemon off;'
  app03:
    build: ./docker/db
    container_name: isucon7-app03
    restart: always
    stdin_open: true
    privileged: true
    volumes:
      - .:/home/isucon/isubata
      - ./docker/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3306
    environment:
      - MYSQL_HOST=localhost
      - USER=root
      - MYSQL_PWD=root
    command: sudo mysqld_safe --port=3306
  bench:
    build: ./docker/db
    container_name: isucon7-bench
    restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 3000
#  mysql:
#    image: mysql:5.7
#    container_name: isucon7-mysql
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#  nginx01:
#    image: nginx
#    container_name: isucon7-nginx01
#    restart: always
#    volumes:
#      - ./files/app/nginx.01.conf:/etc/nginx/nginx.conf
#      - ./files/app/nginx.01.php.conf:/etc/nginx/nginx.php.conf
#    ports:
#      - 8081:80
#    links:
#      - app01
#  nginx02:
#    image: nginx
#    container_name: isucon7-nginx02
#    restart: always
#    volumes:
#      - ./files/app/nginx.02.conf:/etc/nginx/nginx.conf
#      - ./files/app/nginx.02.php.conf:/etc/nginx/nginx.php.conf
#    ports:
#      - 8082:80
#    links:
#      - app02
