version: '3'
services:
  app01:
    build: ./docker
    container_name: isucon7-app01
    restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
    depends_on:
      - mysql
    links:
      - mysql
  app02:
    build: ./docker
    container_name: isucon7-app02
    restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
    depends_on:
      - mysql
    links:
      - mysql
  bench:
    build: ./docker/db
    container_name: isucon7-bench
    restart: always
    stdin_open: true
    volumes:
      - .:/home/isucon/isubata
    ports:
      - 3000
  mysql:
    image: mysql:5.7
    container_name: isucon7-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  nginx01:
    image: nginx
    container_name: isucon7-nginx01
    restart: always
    volumes:
      - ./files/app/nginx.01.conf:/etc/nginx/nginx.conf
      - ./files/app/nginx.01.php.conf:/etc/nginx/nginx.php.conf
    ports:
      - 8081:80
    links:
      - app01
  nginx02:
    image: nginx
    container_name: isucon7-nginx02
    restart: always
    volumes:
      - ./files/app/nginx.02.conf:/etc/nginx/nginx.conf
      - ./files/app/nginx.02.php.conf:/etc/nginx/nginx.php.conf
    ports:
      - 8082:80
    links:
      - app02
